   - name: install apache and php package (CentOS,Ubuntu)
     tags: apache,php,httpd
     package:
       name:
         - "{{ apache_package_name }}"
         - "{{ php_package_name }}"
       state: latest
     

   - name: start and anable apache service
     tags: apache,httpd
     service:
       name: "{{ apache_service }}"
       state: started
       enabled: yes 
          
   - name: change e-mail address for admin
     tags: apache,centos,httpd
     lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin' #this ceking 
       line: ServerAdmin somebody@somewhere.net # replace line this is line
     when: ansible_distribution == "CentOS"
     register: bolean1 # if multiple cheking changed use uniq name this variable

   - name: restart httpd (CentOS and Ubuntu)
     tags: apache,httpd
     service:
       name: "{{ apache_service }}"
       state: restarted
     when: bolean1.changed        

# copy file
   - name: copy html file for site
     tags: apache,apache,apache2,httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644     
       # use host vars "service and package name var name: and package real name. Look at host_vars fooder"